### ISSUE TITLE
_hex_value_parser of gatttool.py fails on python 3.5

### ISSUE THREAD

**Issue by mwick83** [peplin/pygatt#96]
Hi,

I'm currently trying to talk to a BLE device using the pygatt library using the GATTTool backend. I was always getting timeouts connecting, but the device apparently did, what I wanted. So I started digging. I found out that the _hex_value_parser doesn't work on my "Python 3.5.2+ (default, Dec 13 2016, 14:16:35)" debian testing install.

Here is what happens (with pexpect logging to stdout):
```
[                 ][LE]> connect 00:1A:22:09:AE:D5 public
connect 00:1A:22:09:AE:D5 public
Attempting to connect to 00:1A:22:09:AE:D5
Connection successful
[00:1A:22:09:AE:D5][LE]> char-write-req 0x411 4128
char-write-req 0x411 4128
Characteristic value was written successfully
[00:1A:22:09:AE:D5][LE]> sec-level low
sec-level low
[00:1A:22:09:AE:D5][LE]> connect 00:1A:22:09:AE:D5 public
connect 00:1A:22:09:AE:D5 public
Notification handle = 0x0421 value: 02 01 09 00 04 22 
[00:1A:22:09:AE:D5][LE]> 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/pygatt/backends/gatttool/gatttool.py", line 120, in run
    event["callback"](event)
  File "/usr/local/lib/python3.5/dist-packages/pygatt/backends/gatttool/gatttool.py", line 422, in _handle_notification_string
    values = _hex_value_parser(hex_values)
  File "/usr/local/lib/python3.5/dist-packages/pygatt/backends/gatttool/gatttool.py", line 29, in _hex_value_parser
    return bytearray.fromhex(x.decode('utf8'))
AttributeError: 'str' object has no attribute 'decode'
```
Line numbers may be a little off, because of my debugging stuff in it.

If I use the "python 2.7 implementation" of the _hey_value_parser, it doesn't crash anymore, but it still tells me that a timeout occured while connecting, even though the request as been sent correctly and the notification handle answer looks okay:

```
[                 ][LE]> sec-level low
sec-level low
[                 ][LE]> connect 00:1A:22:09:AE:D5 public
connect 00:1A:22:09:AE:D5 public
Attempting to connect to 00:1A:22:09:AE:D5
Connection successful
[00:1A:22:09:AE:D5][LE]> char-write-req 0x411 4126
char-write-req 0x411 4126
Characteristic value was written successfully
[00:1A:22:09:AE:D5][LE]> sec-level low
sec-level low
Notification handle = 0x0421 value: 02 01 09 00 04 26 
[00:1A:22:09:AE:D5][LE]> connect 00:1A:22:09:AE:D5 public
connect 00:1A:22:09:AE:D5 public
[00:1A:22:09:AE:D5][LE]> Timed out connecting to 00:1A:22:09:AE:D5 after 5.0 seconds.
```
Any ideas?
Thanks for your help in advance!
Cheers,
Manuel

**Comment by mwick83** [comment]
Damn, reading the docs helps... I did that again with logging enabled "the-official-way"(tm):

Non-working _hex_value_parser:
```
DEBUG:pygatt.backends.gatttool.gatttool:gatttool_cmd=gatttool -i hci0 -I
INFO:pygatt.backends.gatttool.gatttool:Running...
INFO:pygatt.backends.gatttool.gatttool:Connecting to 00:1A:22:09:AE:D5 with timeout=5.0
DEBUG:pygatt.backends.gatttool.gatttool:Sending cmd=char-write-req 0x411 4126
INFO:pygatt.backends.gatttool.gatttool:Sent cmd=char-write-req 0x411 4126
INFO:pygatt.backends.gatttool.gatttool:Connecting to 00:1A:22:09:AE:D5 with timeout=5.0
INFO:pygatt.device:Received notification on handle=0x421, value=0xb'020109000426'
ERROR:pygatt.backends.gatttool.gatttool:Timed out connecting to 00:1A:22:09:AE:D5 after 5.0 seconds.
```
But using the python 2.7 version doesn't work any better now (I cloned the git version now):
```
DEBUG:pygatt.backends.gatttool.gatttool:gatttool_cmd=gatttool -i hci0 -I
INFO:pygatt.backends.gatttool.gatttool:Running...
INFO:pygatt.backends.gatttool.gatttool:Connecting to 00:1A:22:09:AE:D5 with timeout=5.0
DEBUG:pygatt.backends.gatttool.gatttool:Sending cmd=char-write-req 0x411 4128
INFO:pygatt.backends.gatttool.gatttool:Sent cmd=char-write-req 0x411 4128
INFO:pygatt.backends.gatttool.gatttool:Connecting to 00:1A:22:09:AE:D5 with timeout=5.0
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/manuel/Elektronik/Projekte/home-automation/wireless-network/Software/pc/mqtt_eq3bt_gateway/pygatt/backends/gatttool/gatttool.py", line 132, in run
    event["callback"](event)
  File "/home/manuel/Elektronik/Projekte/home-automation/wireless-network/Software/pc/mqtt_eq3bt_gateway/pygatt/backends/gatttool/gatttool.py", line 467, in _handle_notification_string
    values = _hex_value_parser(hex_values)
  File "/home/manuel/Elektronik/Projekte/home-automation/wireless-network/Software/pc/mqtt_eq3bt_gateway/pygatt/backends/gatttool/gatttool.py", line 35, in _hex_value_parser
    return bytearray.fromhex(x)
TypeError: fromhex() argument must be str, not bytes
```

**Comment by mwick83** [comment]
Never mind, rethinking and restructuring my logic into a single "try/expect" solved the issue. I guess I need to learn a bit more python to understand why the above happened.

Sorry for the noise!
